apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yc-storage-ssd
provisioner: disk-csi-driver.mks.ycloud.io
parameters:
  type: network-ssd
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
