---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-storage-ssd
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-storage-ssd
  resources:
    requests:
      storage: 3Gi
