fullnameOverride: filebeat

daemonset:
  enabled: true

config:
  filebeat.inputs:
  - type: container
    enabled: true
    paths:
    - '/var/log/containers/*.log'
    processors:
    - add_kubernetes_metadata:
        host: '${NODE_NAME}'
        in_cluster: true
    - add_docker_metadata: ~
    - add_host_metadata: ~

  output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: "elastic"
    password: "ElasticSecure123!"
    index: "logs-%{+yyyy.MM.dd}"

  logging.level: info

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
